
flag_management:
  individual_flags:
    - name: "smart-labels"
      carryforward: true
      carryforward_mode: "labels"
      statuses:
        - type: "patch"


cli:
  plugins:
    pycoverage:
      report_type: "json"