name: Codecov-ATS

on:
  pull_request

jobs:
  codecov-ats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
      - name: Install Codecov CLI
        run: |
          python -m pip install --upgrade pip
          pip install codecov-cli
      - name: Create commit in codecov
        run: |
          codecovcli create-commit -t ${{ secrets.CODECOV_TOKEN }}
      - name: Create commit report in codecov
        run: |
          codecovcli create-report -t ${{ secrets.CODECOV_TOKEN }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Static Analysis
        run: |
          codecovcli static-analysis --token ${{ secrets.CODECOV_STATIC_TOKEN }}